-- Slice RI.7 — state-machine + admin extension.
--
-- Migration scope per docs/ri7-state-machine.md §7 and
-- docs/ri7-brief-amendment.md §4 (both decisions-resolved):
--
--   firm_settings: 9 new columns for vendor identity + customer-facing
--                  defaults (vendor name/tagline/address,
--                  quote_number_prefix, T&Cs default, payment terms,
--                  lead time, incoterms, days valid).
--
--   users:         1 new column (phone) — back-filled from HubSpot
--                  owner sync extension in ensureUser at runtime.
--
--   quotes:        12 new columns:
--                  - DEC-1: customer-acceptance event recording (3)
--                  - DEC-4: customer-facing quote_number (1)
--                  - DEC-7: send-time commercial snapshots (5)
--                  - DEC-8: send-time PreparedBy contact snapshot (3)
--
--   Sequence:      quote_number_seq START 1000.
--                  Single-tenant v1 — global counter for The DPS.
--                  See UX_BACKLOG "Multi-tenant quote-number sequence"
--                  for the per-firm-scoped replacement when multi-tenant
--                  becomes real.
--
--   Seed UPDATE:   apply DPS firm-level defaults to the current
--                  firm_settings row (effective_until IS NULL). Per PM
--                  answers in brief amendment §5.1, §5.3-§5.7. T&Cs
--                  default (§5.2) intentionally left NULL — hold gate
--                  before RI.7 PR-to-main; Edward provides canonical
--                  legal text separately. Customer view PdfTerms
--                  renders {tcs-pending} stub for sent quotes until
--                  text lands.
--
-- The ALTER + FK + INDEX statements below were generated by drizzle-kit
-- from src/db/schema.ts edits. The CREATE SEQUENCE + seed UPDATE at
-- the bottom were appended manually (drizzle-kit does not emit
-- sequences or data-shaping statements).

ALTER TABLE "firm_settings" ADD COLUMN "vendor_name" text;--> statement-breakpoint
ALTER TABLE "firm_settings" ADD COLUMN "vendor_tagline" text;--> statement-breakpoint
ALTER TABLE "firm_settings" ADD COLUMN "vendor_address" text;--> statement-breakpoint
ALTER TABLE "firm_settings" ADD COLUMN "quote_number_prefix" text;--> statement-breakpoint
ALTER TABLE "firm_settings" ADD COLUMN "tcs_default" text;--> statement-breakpoint
ALTER TABLE "firm_settings" ADD COLUMN "payment_terms_default" text;--> statement-breakpoint
ALTER TABLE "firm_settings" ADD COLUMN "lead_time_default" text;--> statement-breakpoint
ALTER TABLE "firm_settings" ADD COLUMN "incoterms_default" text;--> statement-breakpoint
ALTER TABLE "firm_settings" ADD COLUMN "days_valid_default" integer;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "customer_accepted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "customer_accepted_tier_id" uuid;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "customer_accepted_recorded_by_user_id" uuid;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "quote_number" text;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "payment_terms_snapshot" text;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "lead_time_snapshot" text;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "incoterms_snapshot" text;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "tcs_snapshot" text;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "days_valid_snapshot" integer;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "prepared_by_name_snapshot" text;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "prepared_by_email_snapshot" text;--> statement-breakpoint
ALTER TABLE "quotes" ADD COLUMN "prepared_by_phone_snapshot" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "phone" text;--> statement-breakpoint
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_customer_accepted_tier_id_quote_tiers_id_fk" FOREIGN KEY ("customer_accepted_tier_id") REFERENCES "public"."quote_tiers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_customer_accepted_recorded_by_user_id_users_id_fk" FOREIGN KEY ("customer_accepted_recorded_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "quotes_quote_number_idx" ON "quotes" USING btree ("quote_number") WHERE quote_number IS NOT NULL;--> statement-breakpoint

-- ---------- quote-number sequence (single-tenant v1) ----------
-- Per CR-SM DEC-4: customer-facing identifier `{prefix}-{counter}`.
-- Counter starts at 1000 (psychological / customer-facing reason —
-- looks established). Prefix lives in firm_settings.quote_number_prefix.
-- Single global sequence; replace with per-firm scoping when multi-tenant.
CREATE SEQUENCE IF NOT EXISTS "quote_number_seq" START WITH 1000 INCREMENT BY 1;--> statement-breakpoint

-- ---------- Seed: DPS firm-level defaults on current firm_settings row ----------
-- Apply to the active row (effective_until IS NULL). Per PM answers in
-- ri7-brief-amendment §5.1, §5.3-§5.7. tcs_default (§5.2) left NULL —
-- hold gate; Edward provides separately before PR-to-main.
--
-- Equivalent to a first-edit admin action; happens at schema-shift time
-- rather than via a separate audit-logged UPDATE since these values are
-- deterministic seed (PM-provided, not derived). RI.7 admin UI is the
-- canonical edit path going forward — subsequent edits audit-log via
-- updateFirmSettingsVendorIdentity / updateFirmSettingsCustomerDefaults.
UPDATE "firm_settings"
SET
  "vendor_name" = 'The DPS',
  "vendor_tagline" = 'Turnkey product development & manufacturing for beauty, health & wellness brands',
  "vendor_address" = '3943 Irvine Blvd, #1129 Irvine, CA 92602',
  "quote_number_prefix" = 'DPS',
  "payment_terms_default" = '50% deposit, 50% on shipment',
  "lead_time_default" = '8–12 weeks from confirmed PO',
  "incoterms_default" = 'FOB Long Beach',
  "days_valid_default" = 30
WHERE "effective_until" IS NULL;
