/**
 * HubSpot vendor library — seed data
 *
 * Source: HubSpot companies WHERE type = VENDOR
 * Pulled: May 6, 2026
 * Total records: 127
 *
 * NOTE: This is RAW seed data, NOT cleaned. Edward + CC need to triage before
 * production use in Slice 13. Specific data quality concerns:
 *
 *   1. ~25 records have empty `name` field (HubSpot record exists but unnamed).
 *      Filter out or backfill before consumption.
 *
 *   2. ~25 records have name = website domain (e.g., "g-locs.com",
 *      "www.magnafolate.com"). Indicates HubSpot record auto-created from
 *      domain match without manual labeling. Real company names need to be
 *      backfilled, or these dropped if not actually used.
 *
 *   3. "Vendor" in HubSpot is broad — covers operational suppliers AND SaaS
 *      subscriptions AND professional services. Slice 13 use case is
 *      Cost Build line dropdowns (packaging / production / freight / raw
 *      ingredients), which is a SUBSET. Likely filtering by `industry` or
 *      adding a custom `cost_line_eligible` flag in HubSpot is needed.
 *
 *      Operational vendor industries to keep:
 *        PACKAGING_AND_CONTAINERS, PAPER_FOREST_PRODUCTS, PRINTING,
 *        COSMETICS, FOOD_BEVERAGES, FOOD_PRODUCTION,
 *        HEALTH_WELLNESS_AND_FITNESS, CONSUMER_GOODS,
 *        MECHANICAL_OR_INDUSTRIAL_ENGINEERING, LOGISTICS_AND_SUPPLY_CHAIN,
 *        PACKAGE_FREIGHT_DELIVERY
 *
 *      Filter OUT for cost-line use case:
 *        COMPUTER_SOFTWARE, INFORMATION_TECHNOLOGY_AND_SERVICES,
 *        TELECOMMUNICATIONS, COMPUTER_HARDWARE, WIRELESS, LEGAL_SERVICES,
 *        ACCOUNTING, HUMAN_RESOURCES, INSURANCE, REAL_ESTATE,
 *        SECURITY_AND_INVESTIGATIONS, UTILITIES, AUTOMOTIVE,
 *        PROFESSIONAL_TRAINING_COACHING, GRAPHIC_DESIGN
 *
 *   4. Address fields are inconsistent — some have line1+city+state+zip
 *      structured, others have everything jammed into address line1.
 *      No automated cleanup attempted; preserved as-is from HubSpot.
 *
 *   5. `preferredVendor` flag is sparse — only 2 records have it set
 *      ("Preferred" string in HubSpot). May be underused or new feature.
 *
 *   6. `vendorRating` is sparse — only 2 records have ratings. Same caveat.
 *
 * Recommended next step: Edward triages this list, applies a
 * `cost_line_eligible: true/false` flag (or equivalent) in HubSpot,
 * then Slice 13 sync filters on that flag.
 */

export interface VendorRecord {
  /** HubSpot company id, primary identifier for sync */
  hubspotId: string;
  name: string | null;
  domain: string | null;
  website: string | null;
  phone: string | null;
  address: {
    line1: string | null;
    line2: string | null;
    city: string | null;
    state: string | null;
    zip: string | null;
    country: string | null;
  };
  /** HubSpot industry enum, e.g., PACKAGING_AND_CONTAINERS, FOOD_BEVERAGES */
  industry: string | null;
  /** Custom HubSpot field, e.g., "Manufacturing", "Plastic Primary", "Rigid Boxes" */
  specialty: string | null;
  description: string | null;
  /** True if HubSpot's preferred_vendor field = "Preferred" */
  preferredVendor: boolean;
  /** HubSpot vendor_rating field — star string, e.g., "★★★★" */
  vendorRating: string | null;
  /** ISO timestamp of last HubSpot record modification */
  hubspotUpdatedAt: string;
}

export const HUBSPOT_VENDOR_SEED: VendorRecord[] = [
  {
    hubspotId: "35632844103",
    name: "Mayer Worldwide Ltd.",
    domain: null,
    website: null,
    phone: "+8615992943094",
    address: {
      line1: "Rm1003,No.1 Zheshang Building,Hong San Road,Hongtu Industrial Zone, Nancheng District,Dongguan City,Guangdong Province,China 523080",
      line2: null, city: null, state: null, zip: null, country: null,
    },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-07-01T22:27:37.900Z",
  },
  {
    hubspotId: "34787668560",
    name: "g-locs.com",
    domain: "g-locs.com", website: "g-locs.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-06-06T16:35:37.258Z",
  },
  {
    hubspotId: "34273823123",
    name: "www.bulksupplements.com",
    domain: "www.bulksupplements.com", website: "www.bulksupplements.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-27T21:16:58.377Z",
  },
  {
    hubspotId: "33938961754",
    name: "Cerusgraphics.com",
    domain: "Cerusgraphics.com", website: "Cerusgraphics.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "PACKAGING_AND_CONTAINERS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-22T23:42:56.976Z",
  },
  {
    hubspotId: "33723501190",
    name: "Athena Industry Limited",
    domain: "www.athena-metal.com", website: "www.athena-metal.com", phone: null,
    address: {
      line1: "No.12 Zhenchang Road, Wusha ChangAn Town", line2: null,
      city: "Dongguan City", state: "China", zip: "523857", country: null,
    },
    industry: "CONSUMER_GOODS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-20T20:17:23.850Z",
  },
  {
    hubspotId: "33255731522",
    name: "TriMas Rieke Packaging",
    domain: null, website: null, phone: null,
    address: { line1: "500 W 7th St", line2: null, city: "Auburn", state: "IN", zip: "46706", country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-09T16:27:37.362Z",
  },
  {
    hubspotId: "33107603251",
    name: "www.magnafolate.com",
    domain: "www.magnafolate.com", website: "www.magnafolate.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-07T19:59:39.193Z",
  },
  {
    hubspotId: "33123964784",
    name: "www.flavorinsights.com",
    domain: "www.flavorinsights.com", website: "www.flavorinsights.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-07T19:58:21.820Z",
  },
  {
    hubspotId: "33107602737",
    name: "Ciranda",
    domain: "www.ciranda.com", website: "www.ciranda.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-22T19:46:23.637Z",
  },
  {
    hubspotId: "33123964249",
    name: "www.jiaherbinc.com",
    domain: "www.jiaherbinc.com", website: "www.jiaherbinc.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-07T19:53:45.982Z",
  },
  {
    hubspotId: "33107602467",
    name: "www.vivion.com",
    domain: "www.vivion.com", website: "www.vivion.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-07T19:51:59.014Z",
  },
  {
    hubspotId: "33123963946",
    name: "www.panasourceusa.com",
    domain: "www.panasourceusa.com", website: "www.panasourceusa.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-07T19:50:18.565Z",
  },
  {
    hubspotId: "33107602086",
    name: "www.maxsunindustry.com",
    domain: "www.maxsunindustry.com", website: "www.maxsunindustry.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-07T19:48:25.780Z",
  },
  {
    hubspotId: "33107601985",
    name: "www.znaturalfoods.com",
    domain: "www.znaturalfoods.com", website: "www.znaturalfoods.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-07T19:47:08.691Z",
  },
  {
    hubspotId: "33107582256",
    name: "Airlite Plastic Co.",
    domain: null, website: null, phone: "+14023417300",
    address: { line1: "6110 Abbott Dr.", line2: null, city: "Omaha", state: "NE", zip: "68110", country: null },
    industry: null, specialty: "Plastic Primary", description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-07T16:43:50.639Z",
  },
  {
    hubspotId: "33070034823",
    name: "Container and Packaging",
    domain: "www.containerandpackaging.com", website: "www.containerandpackaging.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "PACKAGING_AND_CONTAINERS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-06T19:53:34.801Z",
  },
  {
    hubspotId: "32973969335",
    name: null,
    domain: null, website: null, phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "HEALTH_WELLNESS_AND_FITNESS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-05T19:53:43.939Z",
  },
  {
    hubspotId: "32986718520",
    name: "lacore.com",
    domain: "lacore.com", website: "lacore.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-07T18:04:30.749Z",
  },
  {
    hubspotId: "32995233069",
    name: null,
    domain: null, website: null, phone: null,
    address: { line1: "1801 South Industrial Park", line2: null, city: "Van Alstyne", state: "TX", zip: "75495", country: null },
    industry: "HEALTH_WELLNESS_AND_FITNESS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-05T19:51:36.344Z",
  },
  {
    hubspotId: "33004980538",
    name: null,
    domain: null, website: null, phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "COSMETICS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-05T19:48:27.340Z",
  },
  {
    hubspotId: "32995232769",
    name: null,
    domain: null, website: null, phone: null,
    address: { line1: "1815 W 205th St., #303", line2: null, city: "Torrance", state: "CA", zip: "90501", country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-05T19:46:04.419Z",
  },
  {
    hubspotId: "32995219371",
    name: null,
    domain: null, website: null, phone: null,
    address: { line1: "505 South Melrose St.", line2: null, city: "Placentia", state: "CA", zip: "92870-6337", country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-05T17:26:15.485Z",
  },
  {
    hubspotId: "32995219212",
    name: null,
    domain: null, website: null, phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-05T17:23:29.003Z",
  },
  {
    hubspotId: "32973954395",
    name: null,
    domain: null, website: null, phone: null,
    address: { line1: "3470 South Clinton Ave", line2: null, city: "South Plainfield", state: "NJ", zip: "07080", country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-05T17:20:19.604Z",
  },
  {
    hubspotId: "32995218193",
    name: null,
    domain: null, website: null, phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-05T17:11:44.088Z",
  },
  {
    hubspotId: "32909584488",
    name: "Seamanpaper",
    domain: "www.seamanpaper.com", website: "www.seamanpaper.com", phone: null,
    address: { line1: "35 Wilkins Road", line2: null, city: "Gardner", state: "MA", zip: "01440", country: null },
    industry: "PAPER_FOREST_PRODUCTS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-02T23:51:27.902Z",
  },
  {
    hubspotId: "31952094597",
    name: "Cushioneer",
    domain: "www.cushioneer.com", website: "www.cushioneer.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "PACKAGING_AND_CONTAINERS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-04-10T19:53:08.523Z",
  },
  {
    hubspotId: "31009491584",
    name: "Baiya",
    domain: "baiyaplastic.com", website: "baiyaplastic.com", phone: "+8613672717046",
    address: {
      line1: "No. 4 Xingquan Rd, Quanyan Village, Sanxiang Town", line2: null,
      city: "Zhongshan City", state: "Guangdong Province", zip: null, country: null,
    },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-03-13T16:47:39.303Z",
  },
  {
    hubspotId: "30920472721",
    name: "www.rtcopackaging.com",
    domain: "www.rtcopackaging.com", website: "www.rtcopackaging.com", phone: "+8613781596501",
    address: {
      line1: "9th Floor, Building A8, 2555 Xiupu RD, SHA, CHN", line2: null,
      city: null, state: null, zip: null, country: "China",
    },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-03-10T19:56:44.687Z",
  },
  {
    hubspotId: "30752613716",
    name: "Shannon Packaging Company",
    domain: "", website: "https://www.shannonpackaging.com/", phone: "+19095918768",
    address: { line1: "14375 Telephone Ave.", line2: null, city: "Chino", state: "CA", zip: "91710", country: "USA" },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-03-06T17:11:06.644Z",
  },
  {
    hubspotId: "30766776681",
    name: null,
    domain: null, website: null, phone: null,
    address: { line1: "14375 Telephone Ave.", line2: null, city: "Chino", state: "CA", zip: "91710", country: null },
    industry: "PACKAGING_AND_CONTAINERS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-09-30T17:52:04.923Z",
  },
  {
    hubspotId: "30540489254",
    name: "wepackitall.com",
    domain: "wepackitall.com", website: "wepackitall.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-03-27T18:51:52.894Z",
  },
  {
    hubspotId: "29346555016",
    name: "prccopack.com",
    domain: "prccopack.com", website: "prccopack.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-09-02T20:30:36.925Z",
  },
  {
    hubspotId: "28651010133",
    name: "TCR Industries",
    domain: "www.tcrindustries.com", website: "www.tcrindustries.com", phone: "+17145215222",
    address: { line1: "26 Centerpointe Drive #120", line2: null, city: "La Palma", state: "CA", zip: "90623", country: null },
    industry: "FOOD_BEVERAGES", specialty: null, description: "Raw Ingredient Vendor ",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-16T17:20:50.244Z",
  },
  {
    hubspotId: "28313982328",
    name: "nutriient.biz",
    domain: "nutriient.biz", website: "nutriient.biz", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-03-12T22:50:16.130Z",
  },
  {
    hubspotId: "28294048268",
    name: "tier1supplements.com",
    domain: "tier1supplements.com", website: "tier1supplements.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-03-03T20:27:46.124Z",
  },
  {
    hubspotId: "28220038943",
    name: "Refurbco Inc",
    domain: null, website: null, phone: "+19146991817",
    address: { line1: "226 Washington St", line2: null, city: "Mt. Vernon", state: "NY", zip: "10553", country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-02-25T20:11:21.106Z",
  },
  {
    hubspotId: "27985207726",
    name: "McWeb Packaging",
    domain: null, website: null, phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-02-25T20:11:33.752Z",
  },
  {
    hubspotId: "27993103616",
    name: "labelinkusa.com",
    domain: "labelinkusa.com", website: "labelinkusa.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: "Film Supplier",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-02-10T18:41:51.764Z",
  },
  {
    hubspotId: "27580428204",
    name: "pcdcllc.com",
    domain: "pcdcllc.com", website: "pcdcllc.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-12-15T18:13:27.011Z",
  },
  {
    hubspotId: "27219143510",
    name: "rbslg.com",
    domain: "rbslg.com", website: "rbslg.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-04-21T21:00:49.693Z",
  },
  {
    hubspotId: "27113022817",
    name: "Dongguan Jiepuda silicone technology Co., Ltd",
    domain: null, website: null, phone: "+8613538419479",
    address: {
      line1: "No.2 Shipai Avenue West, Tianbian Village, Shipai Town, Dongguan City, Guangdong Province",
      line2: null, city: null, state: null, zip: null, country: "China",
    },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-12-13T20:40:07.415Z",
  },
  {
    hubspotId: "25030504553",
    name: "ultrapure-usa.com",
    domain: "ultrapure-usa.com", website: "ultrapure-usa.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-02-10T19:04:55.226Z",
  },
  {
    hubspotId: "23805257778",
    name: "impackedpackaging.com",
    domain: "impackedpackaging.com", website: "impackedpackaging.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-02-10T19:04:08.342Z",
  },
  {
    hubspotId: "23521036854",
    name: "preciouscosmetics.com",
    domain: "preciouscosmetics.com", website: "preciouscosmetics.com", phone: "+19734784633",
    address: { line1: "40 Meta Lane", line2: null, city: "Lodi", state: "NJ", zip: "07644", country: "USA" },
    industry: null, specialty: "Manufacturing",
    description: "Formulation and manufacturing of Cosmetics and skincare. ",
    preferredVendor: false, vendorRating: "★★★",
    hubspotUpdatedAt: "2025-02-11T18:26:04.540Z",
  },
  {
    hubspotId: "23496890288",
    name: "primarchmfg.com",
    domain: "primarchmfg.com", website: "primarchmfg.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-08-28T22:11:32.869Z",
  },
  {
    hubspotId: "23333694645",
    name: "ingredientsonline.com",
    domain: "ingredientsonline.com", website: "ingredientsonline.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: "FOOD_PRODUCTION", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-21T19:15:34.273Z",
  },
  {
    hubspotId: "23326634937",
    name: "npnutra.com",
    domain: "npnutra.com", website: "npnutra.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:00:12.971Z",
  },
  {
    hubspotId: "23325741426",
    name: "fiflavors.com",
    domain: "fiflavors.com", website: "fiflavors.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:00:14.681Z",
  },
  {
    hubspotId: "23333236749",
    name: "seasalt.com",
    domain: "seasalt.com", website: "seasalt.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:00:15.129Z",
  },
  {
    hubspotId: "23297404345",
    name: "caa.com",
    domain: "caa.com", website: "caa.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-08-28T23:21:34.951Z",
  },
  {
    hubspotId: "23033540473",
    name: "advancedingredients.com",
    domain: "advancedingredients.com", website: "advancedingredients.com", phone: "+18882384647",
    address: { line1: "2030 Main St. ", line2: "Suite 430", city: "Irvine", state: "CA", zip: "92614", country: "United States" },
    industry: null, specialty: null, description: "Raw Ingredients",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:00:12.664Z",
  },
  {
    hubspotId: "23000601360",
    name: "bomotrendline.de",
    domain: "bomotrendline.de", website: "bomo-trendline.de", phone: "+49497403922460",
    address: { line1: "Schönbronner Str. 64", line2: null, city: "Eschbronn", state: null, zip: "78664", country: "Germany" },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:00:12.971Z",
  },
  {
    hubspotId: "22897054238",
    name: "viplogopro.com",
    domain: "viplogopro.com", website: "viplogopro.com", phone: null,
    address: { line1: "21927 Clay Road Ste 600", line2: null, city: "Katy", state: "TX", zip: "77449", country: "USA" },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-02-27T18:00:11.753Z",
  },
  {
    hubspotId: "22886972072",
    name: "maypakcn.com",
    domain: "maypakcn.com", website: "maypakcn.com", phone: "+8618657435151",
    address: { line1: "33shiji Rd, Mazhu Developing Zone,", line2: null, city: "Yuyao City", state: "Zhejiang Province", zip: "315450", country: "China" },
    industry: null, specialty: null,
    description: "Trigger sprayer ， plastic bottle，Deodorant sticks.etc.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-02-27T18:00:12.435Z",
  },
  {
    hubspotId: "22856595338",
    name: "layn-usa.com",
    domain: "layn-usa.com", website: "layn-usa.com", phone: "+19493876840",
    address: { line1: "420 Exchange, Suite 210", line2: null, city: "Irvine", state: "California", zip: "92602", country: "USA" },
    industry: null, specialty: null, description: "Raw ingredients ",
    preferredVendor: true, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:00:12.025Z",
  },
  {
    hubspotId: "22865374514",
    name: "Wellpac",
    domain: "www.wellpac.com", website: "www.wellpac.com", phone: null,
    address: { line1: "Block 1 No.5,Song Xiang Shan Rd.North Song Ling, Duruan District", line2: null, city: "Jiangmen", state: "Guangdong", zip: "529075", country: null },
    industry: null, specialty: null, description: "PET products",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-04-15T18:30:20.562Z",
  },
  {
    hubspotId: "22750945062",
    name: "Best Home 21",
    domain: "besthome21.com", website: "besthome21.com", phone: null,
    address: { line1: "2nd Fl., Everbright B Building,", line2: "No.1585 Juxian Road, High-tech zone", city: "Ningbo", state: "Zhejiang Province", zip: "315100", country: "China" },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:00:15.232Z",
  },
  {
    hubspotId: "22208135854",
    name: "SD Handbags",
    domain: "sdhandbags.com", website: "sdhandbags.com", phone: null,
    address: { line1: "No.1 Zhenyi Road, TaipingZhuang, Shiling town", line2: "Huadu District", city: "Guangzhou", state: "Guangdong province", zip: "510850", country: "China" },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-09-05T22:10:48.116Z",
  },
  {
    hubspotId: "22190002337",
    name: "Certified Laboratories",
    domain: null, website: null, phone: null,
    address: { line1: "3125 N Damon Way", line2: null, city: "Burbank", state: "CA", zip: "91505", country: null },
    industry: "HEALTH_WELLNESS_AND_FITNESS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:00:11.908Z",
  },
  {
    hubspotId: "22186421872",
    name: "Edwards Label",
    domain: "www.edwardslabel.com", website: "www.edwardslabel.com", phone: null,
    address: { line1: "2277 W.Knoll Drive", line2: null, city: "Ventura", state: "CA", zip: "93003", country: "US" },
    industry: "PRINTING", specialty: null, description: "Labels/Pouch/Shrink Sleeve",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:00:14.968Z",
  },
  {
    hubspotId: "22091880742",
    name: "Arizona Custom Blends",
    domain: "acbmfg.com", website: "acbmfg.com", phone: "+14807195550",
    address: { line1: "2130 S. Industrial Park Ave", line2: null, city: "Tempe", state: "AZ ", zip: "85282", country: "USA" },
    industry: null, specialty: "Manufacturing", description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-08-06T18:50:35.079Z",
  },
  {
    hubspotId: "22037463643",
    name: "WJ Paper",
    domain: "wjpaper.com", website: "wjpaper.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-10-14T09:34:28.708Z",
  },
  {
    hubspotId: "21855943853",
    name: "Apackaging Group, LLC",
    domain: "chrislie.com", website: "chrislie.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-08-19T16:52:42.081Z",
  },
  {
    hubspotId: "21631475330",
    name: "Lightning Pack, Inc.",
    domain: "www.lightningpackinc.com", website: "www.lightningpackinc.com", phone: null,
    address: { line1: "132 Beckwith Ave.", line2: null, city: "Paterson", state: "NJ", zip: "07503", country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-06-27T17:13:53.898Z",
  },
  {
    hubspotId: "21374995526",
    name: "Brooke + Whittle",
    domain: "bwhittle.com", website: "bwhittle.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-09-19T17:15:04.796Z",
  },
  {
    hubspotId: "21361260664",
    name: "Unit Pack Company",
    domain: null, website: null, phone: null,
    address: { line1: null, line2: null, city: "Cedar Grove", state: "NJ", zip: "07009", country: null },
    industry: "PACKAGING_AND_CONTAINERS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-10-17T12:29:30.933Z",
  },
  {
    hubspotId: "20402686039",
    name: "Red Dot Packaging",
    domain: "reddotpackaging.com", website: "reddotpackaging.com", phone: null,
    address: { line1: null, line2: null, city: "Ontario", state: "California", zip: "91764", country: "United States" },
    industry: "PAPER_FOREST_PRODUCTS", specialty: null,
    description: "Red Dot Packaging is a trusted leader in providing flexible packaging solutions. With over a decade of experience, we deliver state-of-the-art packaging products that surpass your expectations. We offer a range of packaging options for any product, ens...",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-01T18:43:28.847Z",
  },
  {
    hubspotId: "20401975051",
    name: "Richards Label Co",
    domain: "richardslabel.com", website: "richardslabel.com", phone: "+17145291791",
    address: { line1: "17291 Mount Herrmann Street", line2: null, city: "Fountain Valley", state: "CA", zip: "92708", country: "United States" },
    industry: "PRINTING", specialty: null,
    description: "Richards Label Company, Inc has been family owned and operated since 1979. They specialize in the design and printing of pressure sensitive labels, tags, and flexible packaging.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-01T18:43:26.359Z",
  },
  {
    hubspotId: "20116440132",
    name: "Inotech Therapeutics LLC",
    domain: null, website: null, phone: null,
    address: { line1: null, line2: null, city: "Phoenix", state: "AZ", zip: "85019", country: null },
    industry: "COSMETICS", specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-04-05T19:19:20.583Z",
  },
  {
    hubspotId: "19473499688",
    name: "CTL Printing",
    domain: "ctlprint.com", website: "ctlprint.com", phone: null,
    address: { line1: "1741 W Lincoln Ave", line2: null, city: "Anaheim", state: "CA", zip: "92801", country: "United States" },
    industry: "PRINTING", specialty: null, description: "CTL Printing is a printing company based in Anaheim, CA.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-03-20T15:30:29.624Z",
  },
  {
    hubspotId: "17791162500",
    name: "Blue Ocean Gifts",
    domain: "ezcapeshk.com", website: "ezcapeshk.com", phone: null,
    address: { line1: "No.26,Xinle Road,", line2: "Wusha Village,Changan Town", city: "Dongguan", state: "Guangdong", zip: null, country: "China" },
    industry: null, specialty: null,
    description: "Blue Beauty Technology Limited is a china watchband supplier/manufacturer for many years.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-01T18:55:23.817Z",
  },
  {
    hubspotId: "15335029872",
    name: "Comar",
    domain: "comar.com", website: "comar.com", phone: "8009626627",
    address: { line1: "220 Laurel Road", line2: "201", city: "Voorhees Township", state: "NJ", zip: "08043", country: "United States" },
    industry: "MECHANICAL_OR_INDUSTRIAL_ENGINEERING", specialty: null,
    description: "Comar brings plastic packaging and medical solutions from concept to reality.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-05-21T20:08:01.540Z",
  },
  {
    hubspotId: "14942612819",
    name: "Hwa Hsia Glass Co., Ltd.",
    domain: null, website: null, phone: null,
    address: { line1: null, line2: null, city: "Hsinchu City", state: "Taiwan", zip: "30091", country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-01T18:43:26.489Z",
  },
  {
    hubspotId: "14798343468",
    name: "Superhuman",
    domain: "superhuman.com", website: "superhuman.com", phone: "+1 916-445-1254",
    address: { line1: "465 California St", line2: "STE 300", city: "San Francisco", state: "CA", zip: "94104", country: "United States" },
    industry: "WIRELESS", specialty: null, description: "Superhuman provides the fastest email experience ever made.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-01T18:44:14.756Z",
  },
  {
    hubspotId: "11564389443",
    name: "upbx.net",
    domain: "upbx.net", website: "upbx.net", phone: "6268205410",
    address: { line1: "15051 DON JULIAN RD", line2: null, city: "City Of Industry", state: "CA", zip: "91746", country: "United States" },
    industry: "BUSINESS_SUPPLIES_AND_EQUIPMENT", specialty: null,
    description: "Boxes R US, Inc. was founded in 1996. The company's line of business includes the manufacturing of folding paperboard boxes.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-01T18:50:56.461Z",
  },
  {
    hubspotId: "11503172423",
    name: "Unishippers",
    domain: "unishippers.com", website: "unishippers.com", phone: "+1 801-708-5800",
    address: { line1: "746 E Winchester St", line2: "STE 202", city: null, state: "UT", zip: "84047", country: "United States" },
    industry: "PACKAGE_FREIGHT_DELIVERY", specialty: null,
    description: "Unishippers is a 3PL freight shipping and UPS shipping company.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-02-19T20:46:48.899Z",
  },
  {
    hubspotId: "11491390375",
    name: "Refrens",
    domain: "refrens.com", website: "refrens.com", phone: "+91 97394 32668",
    address: { line1: null, line2: null, city: "Bengaluru", state: "Karnataka", zip: "560100", country: "India" },
    industry: null, specialty: null,
    description: "Refrens is a platform that helps automate business operations such as invoicing, accounting.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-02-15T14:14:22.843Z",
  },
  {
    hubspotId: "11473413159",
    name: "Avodah Law Group",
    domain: "avodahlawgroup.com", website: "avodahlawgroup.com", phone: "+1 714-441-2422",
    address: { line1: "915 W Imperial Hwy", line2: null, city: "Brea", state: "CA", zip: "92821", country: "United States" },
    industry: null, specialty: null, description: "Bringing Your Best to Light",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:34.574Z",
  },
  {
    hubspotId: "11233949963",
    name: "Southern California Edison",
    domain: "sce.com", website: "sce.com", phone: "+1 626-302-0008",
    address: { line1: "800 PO Box", line2: null, city: "Rosemead", state: "CA", zip: "91770", country: "United States" },
    industry: "UTILITIES", specialty: null,
    description: "Southern California Edison (SCE) is a major electric utility company.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:29.938Z",
  },
  {
    hubspotId: "11223205763",
    name: "sam",
    domain: "samlp.com", website: "samlp.com", phone: "+1.916.724.1170",
    address: { line1: "30 Fairbanks", line2: "114", city: "Irvine", state: "CA", zip: "92618", country: "United States" },
    industry: "PROFESSIONAL_TRAINING_COACHING", specialty: null,
    description: "Since 1984, Cybex Security Solutions has been providing integrated security and fire life safety solutions.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-01T18:44:14.768Z",
  },
  {
    hubspotId: "11197808791",
    name: "Jaguar Freight",
    domain: "jaguarfreight.com", website: "jaguarfreight.com", phone: "5162391900",
    address: { line1: "10 5th Avenue", line2: "3rd Floor", city: "New York", state: "NY", zip: "10011", country: "United States" },
    industry: "LOGISTICS_AND_SUPPLY_CHAIN", specialty: null,
    description: "Jaguar Freight is a global freight forwarder and NVOCC.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:40.964Z",
  },
  {
    hubspotId: "10964405091",
    name: "irvine company",
    domain: "irvinecompany.com", website: "irvinecompany.com", phone: "+1 949-720-2000",
    address: { line1: "550 Newport Center Dr", line2: null, city: "Newport Beach", state: "CA", zip: "92660", country: "United States" },
    industry: "REAL_ESTATE", specialty: null, description: "Irvine Company is a leading real estate investment and development firm.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:31.763Z",
  },
  {
    hubspotId: "10930532490",
    name: "AT&T Inc.",
    domain: "att.com", website: "att.com", phone: "+1 210-821-4105",
    address: { line1: "208 South Akard Street", line2: null, city: "Dallas", state: "TX", zip: "75201", country: "United States" },
    industry: "TELECOMMUNICATIONS", specialty: null, description: "AT&T is a top provider of communication and entertainment services globally.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:35.718Z",
  },
  {
    hubspotId: "10929493509",
    name: "Dot Networking",
    domain: "dotcards.net", website: "dotcards.net", phone: null,
    address: { line1: "419 Hindry Avenue", line2: "d", city: "Inglewood", state: "CA", zip: "90301", country: "United States" },
    industry: null, specialty: null, description: "Dot Networking is a company that provides the future of networking through dot cards.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:34.278Z",
  },
  {
    hubspotId: "10920653979",
    name: "ConnectIn Digital",
    domain: "connectindigital.com", website: "connectindigital.com", phone: null,
    address: { line1: null, line2: null, city: "Dubai", state: "Dubai", zip: null, country: "United Arab Emirates" },
    industry: "PROFESSIONAL_TRAINING_COACHING", specialty: null, description: "ConnectIn Digital is a top HubSpot and digital marketing agency.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:31.854Z",
  },
  {
    hubspotId: "10915899699",
    name: "Vestwell",
    domain: "notices.vestwell.com", website: "notices.vestwell.com", phone: "+1 646-902-1401",
    address: { line1: "1410 Broadway", line2: null, city: "New York", state: "NY", zip: "10018", country: "United States" },
    industry: null, specialty: null, description: "Vestwell is a digital recordkeeping platform redefining the way 401(k) plans are powered.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2023-09-14T11:38:49.945Z",
  },
  {
    hubspotId: "10914358366",
    name: "Revalize Inc",
    domain: "revalizesoftware.com", website: "revalizesoftware.com", phone: null,
    address: { line1: "8800 Baymeadows Way West", line2: "500", city: "Jacksonville", state: "FL", zip: "32256", country: "United States" },
    industry: "DESIGN", specialty: null, description: "Revalize is a software company that offers CPQ, PLM, and CAD solutions for manufacturers.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:36.313Z",
  },
  {
    hubspotId: "10911806513",
    name: "Intuit Inc.",
    domain: "us.selfemployed.intuit.com", website: "us.selfemployed.intuit.com", phone: "+1 650-944-6000",
    address: { line1: "2700 Coast Avenue", line2: null, city: "Mountain View", state: "CA", zip: "94043", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Intuit Inc. is a computer software company.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:31.555Z",
  },
  {
    hubspotId: "10876218690",
    name: "Autotrust Repairs Llc",
    domain: "autotrustrepairs.com", website: "autotrustrepairs.com", phone: "+1 936-582-0301",
    address: { line1: "13944 Liberty Street", line2: "3", city: "Montgomery", state: "TX", zip: "77316", country: "United States" },
    industry: "AUTOMOTIVE", specialty: null, description: "Autotrust Repairs is a complete auto care shop in Montgomery and Navasota, TX.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:33.862Z",
  },
  {
    hubspotId: "10873850397",
    name: "Adobe",
    domain: "adobe.com", website: "adobe.com", phone: "+1 408-536-6000",
    address: { line1: "345 Park Avenue", line2: null, city: "San Jose", state: "CA", zip: "95110", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Adobe is a global leader in providing creative, marketing, and document management solutions.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:33.670Z",
  },
  {
    hubspotId: "10850368349",
    name: "Dropbox, Inc",
    domain: "dropbox.com", website: "dropbox.com", phone: "+1 415-986-7057",
    address: { line1: "1800 Owens Street", line2: "200", city: "San Francisco", state: "CA", zip: "94158", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Dropbox is a technology company that builds simple, powerful products for people and businesses.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:38.940Z",
  },
  {
    hubspotId: "10839864142",
    name: "Execubedigital",
    domain: "execubedigital.com", website: "execubedigital.com", phone: null,
    address: { line1: null, line2: null, city: null, state: null, zip: null, country: null },
    industry: null, specialty: null, description: null,
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:30.068Z",
  },
  {
    hubspotId: "10833770124",
    name: "McKernan Packaging Clearing House",
    domain: "mckernan.com", website: "mckernan.com", phone: "8007877587",
    address: { line1: "800 S Rock Blvd", line2: null, city: "Reno", state: "NV", zip: "89502", country: "United States" },
    industry: "FOOD_BEVERAGES", specialty: null,
    description: "McKernan Packaging Clearing House offers wholesale bottles, surplus bottles, and wholesale jars to customers worldwide.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2026-05-01T02:29:37.955Z",
  },
  {
    hubspotId: "10832747672",
    name: "Preferred Concrete Contracting",
    domain: "pcclv.com", website: "pcclv.com", phone: "+1 702-437-3939",
    address: { line1: "1012 East Sharp Circle", line2: null, city: "North Las Vegas", state: "NV", zip: "89030", country: "United States" },
    industry: "CONSTRUCTION", specialty: null, description: "Xtreme Paving & Sealing is a leading provider in Las Vegas, NV.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-02-22T19:19:04.510Z",
  },
  {
    hubspotId: "10824133799",
    name: "usesyncware.com",
    domain: "usesyncware.com", website: "usesyncware.com", phone: null,
    address: { line1: "6 Raffles Quay", line2: null, city: "Singapore", state: null, zip: "048580", country: "Singapore" },
    industry: "COMPUTER_SOFTWARE", specialty: null,
    description: "Syncware uses AI to calculate better picking routes, slotting strategies, and warehouse layouts.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-02-21T20:57:27.420Z",
  },
  {
    hubspotId: "10806657694",
    name: "Wrike",
    domain: "team.wrike.com", website: "wrike.com", phone: "+1 408-329-2019",
    address: { line1: "851 West Cypress Creek Road", line2: "STE 325", city: "Fort Lauderdale", state: "FL", zip: "95113", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Wrike, Inc. is an American project management application service provider.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-02-27T18:00:11.056Z",
  },
  {
    hubspotId: "10744226077",
    name: "Oracle",
    domain: "oracle.com", website: "oracle.com", phone: "+1 737-867-1000",
    address: { line1: "2300 Oracle Way", line2: null, city: "Austin", state: "TX", zip: "78741", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Oracle is a leading American corporation that offers a comprehensive stack of cloud applications and platform services.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-12-16T22:02:45.029Z",
  },
  {
    hubspotId: "10736416514",
    name: "Bdevventures",
    domain: "bdevventures.com", website: "bdevventures.com", phone: null,
    address: { line1: "800 West El Camino Real", line2: "180", city: "Mountain View", state: "CA", zip: "94040", country: "United States" },
    industry: null, specialty: null, description: "BDEV Ventures is a venture capital firm that invests in B2B startups.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-02-19T10:58:48.766Z",
  },
  {
    hubspotId: "10687725344",
    name: "Procurify Technologies Inc",
    domain: "procurify.com", website: "procurify.com", phone: "8884635254",
    address: { line1: "10851 Shellbridge Way", line2: "300", city: "Richmond", state: "British Columbia", zip: "V6X 2W9", country: "Canada" },
    industry: "LEGAL_SERVICES", specialty: null, description: "Procure to Pay Software | Procurify.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:42.313Z",
  },
  {
    hubspotId: "10668308322",
    name: "TruTalent Inc",
    domain: "trutalentinc.com", website: "trutalentinc.com", phone: null,
    address: { line1: "4125 Blackhawk Plaza Circle", line2: "210", city: "Danville", state: "CA", zip: "94506", country: "United States" },
    industry: "HUMAN_RESOURCES", specialty: null, description: "TruTalent Inc is an innovative staffing and recruitment agency in the USA.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-02-19T00:29:53.860Z",
  },
  {
    hubspotId: "10608781453",
    name: "LADINEZ & COMPANY PC",
    domain: "ladinez.com", website: "ladinez.com", phone: "4242784838",
    address: { line1: "21151 South Western Avenue", line2: "156", city: "Torrance", state: "CA", zip: "90501", country: "United States" },
    industry: "ACCOUNTING", specialty: null, description: "LADINEZ & COMPANY PC is a CPA firm based in Torrance, CA.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-02-20T14:39:31.547Z",
  },
  {
    hubspotId: "10601806480",
    name: "Aloware Inc",
    domain: "aloware.com", website: "aloware.com", phone: "+1 855-256-2001",
    address: { line1: "16060 Ventura Boulevard", line2: null, city: "Los Angeles", state: "CA", zip: "91436", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Aloware is a cloud-based contact center solution.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:43.790Z",
  },
  {
    hubspotId: "10599259312",
    name: "Unito",
    domain: "unito.io", website: "unito.io", phone: "+1 548-217-2192",
    address: { line1: "3225 Rue de la Forge", line2: null, city: "Montréal", state: "Québec", zip: "H2L 4X4", country: "Canada" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Unito is a project management tools integrator.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:40.387Z",
  },
  {
    hubspotId: "10577050197",
    name: "Aircall",
    domain: "aircall.io", website: "aircall.io", phone: "+1 866-240-6923",
    address: { line1: "27 West 20th Street", line2: null, city: "New York", state: "NY", zip: "10016", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Aircall is a Global SaaS company providing easy-to-set-up call center software.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:32.683Z",
  },
  {
    hubspotId: "10575325534",
    name: "GleanView LLC",
    domain: "gleanview.com", website: "gleanview.com", phone: "9044176091",
    address: { line1: "11246 Alumni Way", line2: null, city: "Jacksonville", state: "FL", zip: "32246", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "GleanView is an innovative software company that develops cloud-based solutions for small and mid-sized sales and marketing teams.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:42.166Z",
  },
  {
    hubspotId: "10563471424",
    name: "Yuto",
    domain: "szyuto.com", website: "szyuto.com", phone: "86 55 3387 3999",
    address: { line1: "YUTO INDUSTRIAL PARK, SHUITIAN VILLAGE, SHILONGZAI DISTRICT, SHIYAN TOWN", line2: null, city: "Shenzhen Shi", state: "Guangdong Sheng", zip: "518108", country: "China" },
    industry: "PACKAGING_AND_CONTAINERS", specialty: "Rigid Boxes",
    description: "ShenZhen YUTO Packaging Technology Co., Ltd. — research, design, manufacture and distribution of paper printing packaging products.",
    preferredVendor: true, vendorRating: "★★★★",
    hubspotUpdatedAt: "2024-11-20T20:35:36.325Z",
  },
  {
    hubspotId: "10557004890",
    name: "United Parcel Service, Inc.",
    domain: "ups.com", website: "ups.com", phone: "+1 404-828-6000",
    address: { line1: "55 Glenlake Parkway Northeast", line2: null, city: "Sandy Springs", state: "GA", zip: "30328", country: "United States" },
    industry: "LOGISTICS_AND_SUPPLY_CHAIN", specialty: null, description: "UPS is a package delivery company.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:32.358Z",
  },
  {
    hubspotId: "10550281342",
    name: "Qwilr Pty",
    domain: "qwilr.com", website: "qwilr.com", phone: null,
    address: { line1: "7 Hudson Street", line2: "Level 1", city: "Redfern", state: "New South Wales", zip: "2016", country: "Australia" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Qwilr is a web-based sales proposal software.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:30.531Z",
  },
  {
    hubspotId: "10550157235",
    name: "RevOps Inc",
    domain: "revops.io", website: "revops.io", phone: null,
    address: { line1: "4366 25th Street", line2: null, city: "San Francisco", state: "CA", zip: "94114", country: "United States" },
    industry: "INFORMATION_TECHNOLOGY_AND_SERVICES", specialty: null, description: "RevOps is a modern CPQ and Deal Desk platform.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:37.701Z",
  },
  {
    hubspotId: "10549235739",
    name: "Gong.io Ltd",
    domain: "gong.io", website: "gong.io", phone: "+1 516-971-6789",
    address: { line1: "265 Cambridge Avenue", line2: null, city: "Palo Alto", state: "CA", zip: "94306", country: "United States" },
    industry: "PROFESSIONAL_TRAINING_COACHING", specialty: null, description: "Gong is a Revenue Intelligence Platform.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:43.115Z",
  },
  {
    hubspotId: "10545544755",
    name: "Dell",
    domain: "dell.com", website: "dell.com", phone: "+1 512-338-4400",
    address: { line1: "1 Dell Way", line2: null, city: "Round Rock", state: "TX", zip: "47906", country: "United States" },
    industry: "COMPUTER_HARDWARE", specialty: null, description: "Dell is a multinational technology company.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:30.293Z",
  },
  {
    hubspotId: "10545188533",
    name: "Calendly LLC",
    domain: "calendly.com", website: "calendly.com", phone: null,
    address: { line1: "3423 Piedmont Road Northeast", line2: null, city: "Atlanta", state: "GA", zip: "30305", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Calendly is a leading scheduling automation platform.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:32.580Z",
  },
  {
    hubspotId: "10537600355",
    name: "MNA",
    domain: "mnabax.com", website: "mnabax.com", phone: "+1 203-885-7048",
    address: { line1: "337 Kent Road", line2: null, city: "New Milford", state: "CT", zip: "06776", country: "United States" },
    industry: "GRAPHIC_DESIGN", specialty: null, description: "MNA|BAX is a team of specialists in brand strategy, packaging and product design.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:29.187Z",
  },
  {
    hubspotId: "10529204747",
    name: "Apple Inc.",
    domain: "email.apple.com", website: "id.apple.com", phone: "+1 408-996-1010",
    address: { line1: "1 Apple Park Way", line2: null, city: "Cupertino", state: "CA", zip: "95014", country: "United States" },
    industry: "CONSUMER_ELECTRONICS", specialty: null, description: "Apple Inc. is an American multinational technology company.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:45.065Z",
  },
  {
    hubspotId: "10518003863",
    name: "Revenue Growth Consulting",
    domain: "revenuegc.com", website: "revenuegc.com", phone: "+1 214-708-3115",
    address: { line1: null, line2: null, city: null, state: "FL", zip: "33161", country: "United States" },
    industry: "HUMAN_RESOURCES", specialty: null, description: "Revenue Growth Consulting specializes in driving revenue through talent management.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-01T18:44:14.574Z",
  },
  {
    hubspotId: "10512837158",
    name: "SonitrolSAC&OC",
    domain: "sonitroloc.com", website: "sonitroloc.com", phone: "9497681414",
    address: { line1: "23 Mauchly", line2: "STE 100", city: "Irvine", state: "CA", zip: "92618", country: "United States" },
    industry: "SECURITY_AND_INVESTIGATIONS", specialty: null, description: "Sonitrol is one of the top commercial security companies.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:40.362Z",
  },
  {
    hubspotId: "10509107498",
    name: "Beam Benefits",
    domain: "beam.dental", website: "beam.dental", phone: "+1 800-648-1179",
    address: { line1: "226 North 5th Street", line2: "4TH FLOOR", city: "Columbus", state: "OH", zip: "43215", country: "United States" },
    industry: "INSURANCE", specialty: null, description: "Beam Benefits provides streamlined employee benefits.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:31.592Z",
  },
  {
    hubspotId: "10493871725",
    name: "Commissionly",
    domain: "commissionly.io", website: "commissionly.io", phone: "+44 7722 527254",
    address: { line1: "22 Wenlock Road", line2: "Ground Floor, 20", city: "London", state: "Greater London", zip: "N1 7GU", country: "United Kingdom" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Sales Commission Software.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:44.483Z",
  },
  {
    hubspotId: "10493841590",
    name: "Contractbook",
    domain: "contractbook.com", website: "contractbook.com", phone: "+45 89 87 78 38",
    address: { line1: "22 Masnedøgade", line2: null, city: "København", state: "Hovedstaden", zip: "2100", country: "Denmark" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "Contractbook provides contract management software.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:41.959Z",
  },
  {
    hubspotId: "10493379189",
    name: "Chili Piper Inc",
    domain: "chilipiper.com", website: "chilipiper.com", phone: "+1 571-425-3077",
    address: { line1: "228 Park Avenue South", line2: null, city: "New York", state: "NY", zip: "10003", country: "United States" },
    industry: null, specialty: null, description: "Chili Piper is the #1 Meeting Lifecycle Automation platform.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:38.163Z",
  },
  {
    hubspotId: "10493722237",
    name: "PandaDoc Inc",
    domain: "pandadoc.com", website: "pandadoc.com", phone: "+1 800-274-9694",
    address: { line1: "153 Kearny Street", line2: null, city: "San Francisco", state: "CA", zip: "94108", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "PandaDoc is an all-in-one document automation platform.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:42.143Z",
  },
  {
    hubspotId: "10435266588",
    name: "Zapier",
    domain: "send.zapier.com", website: "mail.zapier.com", phone: "+1 877-381-8743",
    address: { line1: "548 Market Street", line2: "STE 508", city: "San Francisco", state: "CA", zip: "18044", country: "United States" },
    industry: "INFORMATION_TECHNOLOGY_AND_SERVICES", specialty: null, description: "Zapier (YC S12) gives people internet superpowers.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:41.600Z",
  },
  {
    hubspotId: "10434335808",
    name: "monday.com",
    domain: "monday.com", website: "monday.com", phone: null,
    address: { line1: "6 Yitzhak Sadeh Street", line2: null, city: "Tel Aviv-Yafo", state: "Tel Aviv District", zip: null, country: "Israel" },
    industry: null, specialty: null, description: "monday.com is an open platform democratizing software for work management.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:29.650Z",
  },
  {
    hubspotId: "10433810308",
    name: "MRI software",
    domain: "com.ng1.angus.mrisoftware.com", website: "ng1v4.angus.mrisoftware.com", phone: "+1 216-825-6607",
    address: { line1: "28925 Fountain Parkway", line2: null, city: "Solon", state: "OH", zip: "44139", country: "United States" },
    industry: "COMPUTER_SOFTWARE", specialty: null, description: "MRI Software, LLC is a provider of real estate and investment management software.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2025-01-23T02:32:42.180Z",
  },
  {
    hubspotId: "10427901700",
    name: "ZAGG",
    domain: "zagg.com", website: "zagg.com", phone: "+1 801-263-0699",
    address: { line1: "910 W Legacy Center Way", line2: "", city: "Midvale", state: "UT", zip: "84047", country: "United States" },
    industry: "WIRELESS", specialty: null, description: "ZAGG Brands creates tech accessories.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-01T18:43:27.858Z",
  },
  {
    hubspotId: "10427990623",
    name: "Fat Straws",
    domain: "fatstraws.net", website: "fatstraws.net", phone: "+1 972-403-7403",
    address: { line1: "6509 West Park Boulevard", line2: null, city: "Plano", state: "TX", zip: "75093", country: "United States" },
    industry: "FOOD_BEVERAGES", specialty: null, description: "Fat Straws is a beverage company that specializes in serving bubble tea.",
    preferredVendor: false, vendorRating: null,
    hubspotUpdatedAt: "2024-11-01T18:43:27.842Z",
  },
];
